name: "Install poetry and dependencies"
description: "Install poetry and dependencies"
runs:
  using: "composite"
  steps:
    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ env.POETRY_VERSION }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: .venv
        key: pydeps-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      shell: bash
      run: echo $PWD; poetry install --no-interaction --no-root
      if: steps.cache-deps.outputs.cache-hit != 'true'