name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

env:
  POETRY_VERSION: 1.7.1

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: /.github/workflows/poetry-composite-action
      - name: Run MyPy
        run: |
          source .venv/bin/activate \ 
          mypy ./custom_components/powercalc
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@v3
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.14
          src: './custom_components/powercalc'