name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: fetch-latest-release
        name: Fetch latest release
        uses: InsonusK/get-latest-release@v1.0.1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      - name: Dump latest release
        env:
          LATEST_RELEASE: ${{ steps.fetch-latest-release.outputs.latest-release }}
        run: echo "$LATEST_RELEASE"