name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2
        with:
          github_token: ${{ github.token }}
      - name: Dump latest release
        env:
          LATEST_RELEASE: ${{ steps.latest.outputs.tag_name }}
        run: echo "$LATEST_RELEASE"