name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/poetry-composite-action
      - name: Prepare test env
        run: bash tests/setup.sh
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.powercalc \
            --cov-report xml \
            -o console_output_style=count \
            -p no:sugar \
            tests
          coverage lcov
      
      - name: Upload Coverage Results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov