name: Test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements.test.txt
      - name: Run tests
        run: bash tests/setup.sh
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.powercalc \
            -o console_output_style=count \
            -p no:sugar \
            tests