name: validate-light-model

on:
#  push:
#    paths:
#      - '**.csv.gz'
  pull_request:
    paths:
       - '**.csv.gz'

jobs:
  validate-lut:
    name: Validate LUT CSV files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd .github/scripts/lut_validator
        npm install
    - name: Validate LUT CSV files
      run: node .github/scripts/lut_validator/validate.js
  visualize:
    name: Add plot to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/poetry-composite-action
        with:
          directory: './utils/visualize'
          python_version: '3.11'
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ github.token }}
          outputFormat: 'space-delimited'
      - run: cd ./utils/visualize && poetry run python plot.py '${{ github.workspace }}/custom_components/powercalc/data/test/test/color_temp.csv.gz' --output=test1.png
      - run: |
          cd ./utils/visualize
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            if [ "$file" == "*.csv.gz" ]
            then
              echo "Changed Files - ${file}."
              poetry run python plot.py $github_workspace/${file} --output=test.png
            fi
          done
      - name: Upload failed tests
        uses: edunad/actions-image@v2.0.0
        with:
            path: '/utils/visualize/*.png'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: 'Failed E2E tests 🙀'
            annotationLevel: 'failure'
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: light-model
