name: validate-light-model

on:
#  push:
#    paths:
#      - '**.csv.gz'
  pull_request:
    paths:
       - '**.csv.gz'

jobs:
  validate-lut:
    name: Validate LUT CSV files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd .github/scripts/lut_validator
        npm install
    - name: Validate LUT CSV files
      run: node .github/scripts/lut_validator/validate.js
  visualize:
    name: Add plot to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: ./.github/workflows/poetry-composite-action
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ github.token }}
          outputFormat: 'space-delimited'
      - run: |
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            if [ "$file" == "*.txt" ]
            then
              echo "Changed Files - ${file}."
              poetry run python ./utils/visualise/plot.py ${file} --output=test.png
            fi
          done
      - name: Upload failed tests
        uses: edunad/actions-image@v2.0.0
        with:
            path: './*.png'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: 'Failed E2E tests 🙀'
            annotationLevel: 'failure'
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: light-model
