name: validate-light-model

on:
  pull_request:
    paths:
       - '**.csv.gz'

jobs:
  validate-lut:
    name: Validate LUT CSV files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd .github/scripts/lut_validator
        npm install
    - name: Validate LUT CSV files
      run: node .github/scripts/lut_validator/validate.js
  visualize:
    name: Add plot to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/poetry-composite-action
        with:
          directory: './utils/visualize'
          python_version: '3.11'
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ github.token }}
          outputFormat: 'space-delimited'
      - run: cd ./utils/visualize && poetry run python plot.py '${{ github.workspace }}/custom_components/powercalc/data/test/test/color_temp.csv.gz' --output=test1.png
      - run: |
          cd ./utils/visualize
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            if [ "$file" == "*.csv.gz" ]
            then
              echo "Changed Files - ${file}."
              poetry run python plot.py '$github_workspace/${file}' --output=test.png
            fi
          done
      - name: Upload the plots to Imgur
        uses: devicons/public-upload-to-imgur@v2.2.2
        id: imgur_step
        with:
          path: ./utils/visualize/*.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: Comment on the PR about the result
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        env:
          IMG_URL: ${{ fromJSON(steps.imgur_step.outputs.imgur_urls)[0] }}
          MESSAGE: |
            Here is the picture that was uploaded:
            ![Image]({0})
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{format(env.MESSAGE, env.IMG_URL)}}
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: light-model
